=== XDgierman/school/databases/ćwiczenia/ćwiczenie 4/Klienci.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Klienci" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Klienci">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="IDklienta" index-key="IDklienta " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="IDwojewodztwa" index-key="IDwojewodztwa " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="MiastoKlienta" index-key="MiastoKlienta " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="NazwiskoKlienta" index-key="NazwiskoKlienta " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="PrimaryKey" index-key="IDklienta " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAAAGN6EEi6g+T4j4NMdGIL8jAAAAAK1yBLIM7eNAbABpAGUAbgBLAGwA
aQBlAG4AYwBpAAAAAAAAADIJxwZ4eYlDtW8wIWLlWjwHAAAABjehBIuoPk+I+DTH
RiC/I0kARABrAGwAaQBlAG4AdABhAAAAAAAAAAAC6fp2ip9HqKXhPyB4ueAHAAAA
BjehBIuoPk+I+DTHRiC/I0kAbQBpAGUASwBsAGkAZQBuAHQAYQAAAAAAAAC4II+a
TAaQSb3Tzgo18mXcBwAAAAY3oQSLqD5PiPg0x0YgvyNOAGEAegB3AGkAcwBrAG8A
SwBsAGkAZQBuAHQAYQAAAAAAAAAf7QTyaxvZEZ3QABBa8YibAAAAAIiLBNo3C+NA
AI0vAMRsQgBXAG8AagBlAHcAbwBkAHoAdAB3AGEAAAAAAAAAIO0E8msb2RGd0AAQ
WvGImwcAAAAf7QTyaxvZEZ3QABBa8YibSQBEAFcAbwBqAGUAdwBvAGQAegB0AHcA
YQAAAAAAAAAh7QTyaxvZEZ3QABBa8YibBwAAAB/tBPJrG9kRndAAEFrxiJtXAG8A
agBlAHcAbwBkAHoAdAB3AG8AAAAAAAAACWj5fCxSS02CEh5/T0uJVQcAAAAGN6EE
i6g+T4j4NMdGIL8jSQBEAFcAbwBqAGUAdwBvAGQAegB0AHcAYQAAAAAAAAC8uVNM
MuT3TpA9DRZ7iEwgBwAAAAY3oQSLqD5PiPg0x0YgvyNLAG8AZABQAG8AYwB6AHQA
bwB3AHkASwBsAGkAZQBuAHQAYQAAAAAAAACa+tUYbHZoQpIHytkELwbFBwAAAAY3
oQSLqD5PiPg0x0YgvyNNAGkAYQBzAHQAbwBLAGwAaQBlAG4AdABhAAAAAAAAABEK
eyIQphFFvVjox+JeghQHAAAABjehBIuoPk+I+DTHRiC/I1UAbABpAGMAYQBLAGwA
aQBlAG4AdABhAAAAAAAAAMBw68EdvwBPhghqeleoJrAHAAAABjehBIuoPk+I+DTH
RiC/I04AcgBEAG8AbQB1AEsAbABpAGUAbgB0AGEAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAwAAAAEAAAAAAAAAAAAAAAAAAAAAAA=
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="GUID" type="9" value="DvpbCAH+XU+P36h7ojmpeA==
"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="100"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="IDklienta" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1455"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Caption" type="12" value="ID klienta"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="ImieKlienta" minOccurs="1" od:jetType="text" od:sqlSType="nvarchar" od:nonNullable="yes">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="1"/>
<od:fieldProperty name="Caption" type="12" value="Imię"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="NazwiskoKlienta" minOccurs="1" od:jetType="text" od:sqlSType="nvarchar" od:nonNullable="yes">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="1"/>
<od:fieldProperty name="Caption" type="12" value="Nazwisko"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="IDwojewodztwa" minOccurs="1" od:jetType="longinteger" od:sqlSType="int" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2070"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Caption" type="12" value="Województwo"/>
<od:fieldProperty name="Required" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT [Wojewodztwa].[IDwojewodztwa], [Wojewodztwa].[NazwaWojewodztwa] FROM [Wojewodztwa] ORDER BY [NazwaWojewodztwa];"/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="2"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;1440"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="1440twip"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="0"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="KodPocztowyKlienta" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="Caption" type="12" value="Kod poczt."/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="InputMask" type="10" value="00/000;0;&quot; &quot;"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="20"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="MiastoKlienta" minOccurs="1" od:jetType="text" od:sqlSType="nvarchar" od:nonNullable="yes">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="1"/>
<od:fieldProperty name="Caption" type="12" value="Miasto"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="UlicaKlienta" minOccurs="1" od:jetType="text" od:sqlSType="nvarchar" od:nonNullable="yes">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1515"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Caption" type="12" value="Ulica"/>
<od:fieldProperty name="Required" type="1" value="1"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="NrDomuKlienta" minOccurs="1" od:jetType="text" od:sqlSType="nvarchar" od:nonNullable="yes">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1590"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Caption" type="12" value="Numer domu"/>
<od:fieldProperty name="Required" type="1" value="1"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="3"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="10"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== XDgierman/school/databases/ćwiczenia/ćwiczenie 4/Klienci.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Klienci.xsd" generated="2018-09-11T15:01:25">
<Klienci>
<IDklienta>1</IDklienta>
<ImieKlienta>Jan</ImieKlienta>
<NazwiskoKlienta>Kowalski</NazwiskoKlienta>
<IDwojewodztwa>12</IDwojewodztwa>
<KodPocztowyKlienta>43-190</KodPocztowyKlienta>
<MiastoKlienta>Mikołów</MiastoKlienta>
<UlicaKlienta>Rybnicka</UlicaKlienta>
<NrDomuKlienta>44</NrDomuKlienta>
</Klienci>
<Klienci>
<IDklienta>2</IDklienta>
<ImieKlienta>Piotr</ImieKlienta>
<NazwiskoKlienta>Nowak</NazwiskoKlienta>
<IDwojewodztwa>12</IDwojewodztwa>
<KodPocztowyKlienta>40-265</KodPocztowyKlienta>
<MiastoKlienta>Katowice</MiastoKlienta>
<UlicaKlienta>Mikołowska</UlicaKlienta>
<NrDomuKlienta>150</NrDomuKlienta>
</Klienci>
<Klienci>
<IDklienta>3</IDklienta>
<ImieKlienta>Marek</ImieKlienta>
<NazwiskoKlienta>Niedzielan</NazwiskoKlienta>
<IDwojewodztwa>12</IDwojewodztwa>
<KodPocztowyKlienta>43-190</KodPocztowyKlienta>
<MiastoKlienta>Mikołów</MiastoKlienta>
<UlicaKlienta>Krakowksa</UlicaKlienta>
<NrDomuKlienta>100</NrDomuKlienta>
</Klienci>
<Klienci>
<IDklienta>4</IDklienta>
<ImieKlienta>Katarzyna</ImieKlienta>
<NazwiskoKlienta>Więcek</NazwiskoKlienta>
<IDwojewodztwa>6</IDwojewodztwa>
<KodPocztowyKlienta>30-200</KodPocztowyKlienta>
<MiastoKlienta>Kraków</MiastoKlienta>
<UlicaKlienta>Smocza</UlicaKlienta>
<NrDomuKlienta>3/10</NrDomuKlienta>
</Klienci>
<Klienci>
<IDklienta>5</IDklienta>
<ImieKlienta>Maria</ImieKlienta>
<NazwiskoKlienta>Karolczak</NazwiskoKlienta>
<IDwojewodztwa>1</IDwojewodztwa>
<KodPocztowyKlienta>45-678</KodPocztowyKlienta>
<MiastoKlienta>Wrocław</MiastoKlienta>
<UlicaKlienta>Katowicka</UlicaKlienta>
<NrDomuKlienta>24</NrDomuKlienta>
</Klienci>
<Klienci>
<IDklienta>6</IDklienta>
<ImieKlienta>Adam</ImieKlienta>
<NazwiskoKlienta>Maliniak</NazwiskoKlienta>
<IDwojewodztwa>12</IDwojewodztwa>
<KodPocztowyKlienta>40-710</KodPocztowyKlienta>
<MiastoKlienta>Katowice</MiastoKlienta>
<UlicaKlienta>Słupska</UlicaKlienta>
<NrDomuKlienta>35</NrDomuKlienta>
</Klienci>
<Klienci>
<IDklienta>7</IDklienta>
<ImieKlienta>Andrzej</ImieKlienta>
<NazwiskoKlienta>Nowak</NazwiskoKlienta>
<IDwojewodztwa>12</IDwojewodztwa>
<KodPocztowyKlienta>43-190</KodPocztowyKlienta>
<MiastoKlienta>Tychy</MiastoKlienta>
<UlicaKlienta>Dębowa</UlicaKlienta>
<NrDomuKlienta>20</NrDomuKlienta>
</Klienci>
<Klienci>
<IDklienta>8</IDklienta>
<ImieKlienta>Antonina</ImieKlienta>
<NazwiskoKlienta>Kowalczyk</NazwiskoKlienta>
<IDwojewodztwa>12</IDwojewodztwa>
<KodPocztowyKlienta>44-500</KodPocztowyKlienta>
<MiastoKlienta>Katowice</MiastoKlienta>
<UlicaKlienta>Kopernika</UlicaKlienta>
<NrDomuKlienta>50/21</NrDomuKlienta>
</Klienci>
<Klienci>
<IDklienta>9</IDklienta>
<ImieKlienta>Leszek</ImieKlienta>
<NazwiskoKlienta>Pusz</NazwiskoKlienta>
<IDwojewodztwa>7</IDwojewodztwa>
<KodPocztowyKlienta>02-770</KodPocztowyKlienta>
<MiastoKlienta>Warszawa</MiastoKlienta>
<UlicaKlienta>Wiejska</UlicaKlienta>
<NrDomuKlienta>50</NrDomuKlienta>
</Klienci>
<Klienci>
<IDklienta>10</IDklienta>
<ImieKlienta>Kunegunda</ImieKlienta>
<NazwiskoKlienta>Piszczak</NazwiskoKlienta>
<IDwojewodztwa>12</IDwojewodztwa>
<KodPocztowyKlienta>44-521</KodPocztowyKlienta>
<MiastoKlienta>Katowice</MiastoKlienta>
<UlicaKlienta>Andrzeja</UlicaKlienta>
<NrDomuKlienta>56</NrDomuKlienta>
</Klienci>
<Klienci>
<IDklienta>11</IDklienta>
<ImieKlienta>Jan</ImieKlienta>
<NazwiskoKlienta>Jankowski</NazwiskoKlienta>
<IDwojewodztwa>12</IDwojewodztwa>
<KodPocztowyKlienta>43-190</KodPocztowyKlienta>
<MiastoKlienta>Mikołów</MiastoKlienta>
<UlicaKlienta>Jasna</UlicaKlienta>
<NrDomuKlienta>12</NrDomuKlienta>
</Klienci>
</dataroot>
